### ISSUE TITLE
logOutCurrentUser error

### ISSUE THREAD

**Issue by benaneesh** [xeieshan/SwiftUserManager#1]
First of all, awesome stuff!

 `logOutCurrentUser` calls `setCurrentUser(newCurrentUser: nil)` 
in which 
`assert(newCurrentUser != nil, "Trying to set current user to nil! Use [MOUser logOutCurrentUser] instead!")` gets triggered.

I guess remove the call to `setCurrentUser` in `logOutCurrentUser`?

**Comment by xeieshan** [comment]
Pull latest commit, its fixed.

Thanks anyways.
